GHI #20 Fix indentation

diff --git a/.github/workflows/reusable-test-warning.yml b/.github/workflows/reusable-test-warning.yml
--- a/.github/workflows/reusable-test-warning.yml
+++ b/.github/workflows/reusable-test-warning.yml
@@ -42,20 +42,20 @@ jobs:
         shell: bash
         run: |
           # checks input is not empty
-            check_input() {
-              input_name="${1}"
-              input_value="${2}"
-              if [[ -z "${input_value}" ]]; then
-                echo "Error: required input '${input_name}' is empty or was not specified."
-                exit 1
-              else
-                echo "${input_name}: ${input_value}"
-              fi
-            }
+          check_input() {
+            input_name="${1}"
+            input_value="${2}"
+            if [[ -z "${input_value}" ]]; then
+              echo "Error: required input '${input_name}' is empty or was not specified."
+              exit 1
+            else
+              echo "${input_name}: ${input_value}"
+            fi
+          }
 
-            # apply function to all inputs
-            check_input "preset" "${{ inputs.preset }}"
-            check_input "architecture" "${{ inputs.architecture }}"
-            check_input "triple" "${{ inputs.triple }}"
-            check_input "cmake_build_shared" "${{ inputs.cmake_build_shared }}"
-            check_input "patomic_path" "${{ inputs.patomic_path }}"
+          # apply function to all inputs
+          check_input "preset" "${{ inputs.preset }}"
+          check_input "architecture" "${{ inputs.architecture }}"
+          check_input "triple" "${{ inputs.triple }}"
+          check_input "cmake_build_shared" "${{ inputs.cmake_build_shared }}"
+          check_input "patomic_path" "${{ inputs.patomic_path }}"
